### PR TITLE
Make host and guest paths configurable

### PR DESCRIPTION
**Pull request by trizz**
As mentioned in [this](https://github.com/mhallin/vagrant-notify-forwarder/issues/3) issue, I've had trouble with the folders that are being watched. This PR makes both the host as well as the guest path configurable. If no configuration is provided, the default paths are used (as in the current release).

> Note: this is the first time I've done anything in Ruby. Perhaps it could be better, but it is working the way I want.

### CODE REVIEW

**Comment by robbinjanssen** [comment]
+1

**Comment by mhallin** [comment]
This is an interesting PR, but the default behavior should in the current release be to watch all folders configured with `synced_folder`.

Also, if you use this to set `host_path` or `guest_path` it seems to override the watch for _all_ synced folders. Is this intentional?

**Comment by trizz** [comment]
Unfortunately, it doesn't. The default behaviour will start `notify-forwarder` as follows:

```
/Users/MyUser/.vagrant.d/tmp/notify-forwarder_osx_x64 watch -c 127.0.0.1:29324 /Users/MyUser/VMs/devbox /vagrant
```

So it watches for changes in `/Users/MyUser/VMs/devbox` and everything beneath it. But my source is located in `/Users/MyUser/code/`. Also, it maps the changes to the `/vagrant` folder in the VM, but my synced folder is set up to use `/srv/www`.

My synced folder is configured like this:

```
config.vm.synced_folder "~/code", "/srv/www", type: "nfs"
```

> Also, if you use this to set host_path or guest_path it seems to override the watch for all synced folders. Is this intentional?

No, this isn't intentional, I just didn't know that it was supposed to watch all configured synced folders (which it apparently doesn't do in my setup :wink: )

**Comment by trizz** [comment]
Apparently I was running an older version of Vagrant (1.7.*). After updating to 1.8.1 the plugin works as expected (and watches both the default as the configured synced folder).

I'm closing this PR, as there isn't any problem anymore :smile:

**Comment by sinharaksh1t** [comment]
So did this PR finally not get merged? I'm having a similar issue where my files are synced like this:
```config.vm.synced_folder "code/", "/code", create: true```
So when I'm running the build system within the vagrant environment, it does not hot reload once I make changes on the VSCode running on my Mac. If it's easier to tackle this concern if I opened another issue then lmk and I'll be happy to do so! Thanks!

**Pull request closed without merging**
